from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os
import datetime

class ReportingService:
    @staticmethod
    def generate_report(candidate_name, results_data):
        filename = f"report_{candidate_name.replace(' ', '_')}.pdf"
        c = canvas.Canvas(filename, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFillColorRGB(0.06, 0.07, 0.1) # Dark theme matching UI
        c.rect(0, height-100, width, 100, fill=1)
        
        c.setFillColorRGB(1, 1, 1)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height-60, "RECRUIT-AI EXECUTIVE REPORT")
        
        c.setFont("Helvetica", 10)
        c.drawString(width-180, height-40, "CONFIDENTIAL")
        c.drawString(width-180, height-55, datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))

        # Candidate Info
        c.setFillColorRGB(0, 0, 0)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height-140, f"Candidate Information: {candidate_name}")
        c.line(50, height-145, 250, height-145)
        
        # Scoring Summary
        y = height - 180
        c.setFont("Helvetica-Bold", 12)
        c.drawString(70, y, "Performance Metric")
        c.drawString(250, y, "Score")
        c.line(50, y-5, 300, y-5)
        
        c.setFont("Helvetica", 12)
        metrics = [
            ("Interview Relevance", f"{results_data['interview_score']}%"),
            ("Behavioral Integrity", f"{results_data['behavior_score']}%"),
            ("Total Compatibility", f"{results_data['total_score']}%")
        ]
        
        for label, score in metrics:
            y -= 25
            c.drawString(70, y, label)
            c.drawString(250, y, score)

        # Risk Assessment
        y -= 50
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Risk Assessment Output")
        
        risk_color = (0.1, 0.7, 0.1) if results_data['risk_level'] == 'Low' else (0.8, 0, 0)
        c.setFillColorRGB(*risk_color)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(250, y, results_data['risk_level'].upper())
        
        # Alert Summary
        c.setFillColorRGB(0, 0, 0)
        y -= 40
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, f"Total Alerts Logged: {results_data['alert_count']}")
        
        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(width/2 - 40, 30, "Generated by RecruitAI Autonomous Intelligence")
        
        c.save()
        return filename

reporting_service = ReportingService()
