import streamlit as st
import pandas as pd
import sys
import os
import requests

# Add backend to path so we can import models if needed, though using API is better
sys.path.append(os.path.join(os.path.dirname(__file__), 'backend'))
try:
    from backend.database import SessionLocal
    import backend.models as models
except ImportError:
    SessionLocal = None
    models = None

st.set_page_config(page_title="RecruitAI Admin Dashboard", page_icon="👔", layout="wide")

# 🎨 Custom CSS for Admin Dashboard
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');
    
    .stApp {
        background-color: #0F172A;
        color: #F8FAFC;
        font-family: 'Outfit', sans-serif;
    }
    .metric-card {
        background: rgba(255, 255, 255, 0.05);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 12px;
        padding: 20px;
        text-align: center;
        box-shadow: 0 4px 15px rgba(0,0,0,0.2);
    }
    .metric-value {
        font-size: 2.5rem;
        font-weight: 700;
        color: #10B981;
    }
    .metric-label {
        font-size: 1rem;
        color: #94A3B8;
    }
</style>
""", unsafe_allow_html=True)

st.title("👔 RecruitAI Admin & Recruiter Dashboard")
st.markdown("Welcome to the Recruiter Portal. View candidate interviews, scores, and integrity reports generated by the **LangGraph Multi-Agent system**.")

# Fetch data from SQLite
@st.cache_data(ttl=5)
def get_data():
    if not SessionLocal:
        return pd.DataFrame()
        
    db = SessionLocal()
    try:
        interviews = db.query(models.Interview).all()
        
        data = []
        for iv in interviews:
            c = db.query(models.Candidate).filter(models.Candidate.id == iv.candidate_id).first()
            if c:
                data.append({
                    "Interview ID": iv.id,
                    "Candidate Name": c.name,
                    "Email": c.email,
                    "Role": getattr(iv, 'target_role', 'N/A'),
                    "Score": iv.total_score,
                    "Status": iv.status,
                    "Date": iv.created_at.strftime("%Y-%m-%d %H:%M") if iv.created_at else "N/A"
                })
        return pd.DataFrame(data)
    except Exception as e:
        st.error(f"Database error: {e}")
        return pd.DataFrame()
    finally:
        db.close()

df = get_data()

# --- TOP METRICS ---
col1, col2, col3 = st.columns(3)
with col1:
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-label">Total Candidates</div>
        <div class="metric-value">{len(df) if not df.empty else 0}</div>
    </div>
    """, unsafe_allow_html=True)
with col2:
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-label">Completed Interviews</div>
        <div class="metric-value">{len(df[df['Status'] == 'completed']) if not df.empty else 0}</div>
    </div>
    """, unsafe_allow_html=True)
with col3:
    avg_score = f"{df['Score'].mean():.1f}" if not df.empty and not pd.isna(df['Score'].mean()) else "N/A"
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-label">Average Score</div>
        <div class="metric-value" style="color: #3B82F6;">{avg_score}</div>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<br><br>", unsafe_allow_html=True)

# --- LEADERBOARD ---
st.subheader("🏆 Candidate Leaderboard")
if not df.empty:
    # Stylize the dataframe
    st.dataframe(
        df.sort_values(by="Score", ascending=False), 
        use_container_width=True,
        hide_index=True
    )
else:
    st.info("No interview data found yet. Candidates need to complete the React interview first.")

st.divider()

# --- REPORT GENERATION ---
st.subheader("📄 View Detailed PDF Reports")
st.markdown("The **Reporter Agent** compiles transcripts, evaluator scores, and proctoring alerts into a final PDF.")

if not df.empty:
    col_a, col_b = st.columns([3, 1])
    with col_a:
        selected_id = st.selectbox("Select Interview to view report", df["Interview ID"].tolist())
    with col_b:
        st.markdown("<br>", unsafe_allow_html=True) # padding
        if st.button("Generate & Download PDF", use_container_width=True):
            st.success(f"Connecting to Reporter Agent for Interview #{selected_id}...")
            
            # Ping backend to get report
            try:
                # Normally we would do:
                # response = requests.get(f"http://127.0.0.1:8000/interview/{selected_id}/report")
                st.info("In production, this fetches the generated report from the backend Reporter Agent.")
            except Exception as e:
                st.error("Backend offline. Ensure FastAPI is running.")
